# Generated by Django 5.1.7 on 2025-03-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_pair", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
